### ISSUE TITLE
Support to Meteor 2.3

### ISSUE THREAD

**Issue by ricaragao** [illusionfield/meteor-restivus#1]
It's necessary update the package to be used in Meteor 2.3+

See:

```
$ meteor add illusionfield:restivus
 => Errors while adding packages:             
                                              
While selecting package versions:
error: Conflict: Constraint accounts-password@1.5.1 is not satisfied by accounts-password 2.0.1.
Constraints on package "accounts-password":
* accounts-password@2.0.0 <- top level
* accounts-password@~2.0.0 <- top level
* accounts-password@1.5.1 <- illusionfield:restivus 0.9.2

$ meteor --version         
Meteor 2.3.5
```

**Comment by illusionfield** [comment]
I'm sorry that you encountered compatibility issues. Unfortunately, I likely won't be able to support `Meteor 2.x` versions in the future. However, since I also need a good REST solution for Meteor 3.0+, I will look for alternatives. If I find a good initiative, I will contribute to its development; otherwise, I will build a completely new package.
